workflows:
    ios-sonarcloud:
      name: iOS sonarcloud
      environment:
        vars:
            XCODE_PROJECT: "TestCIZ.xcodeproj"
            XCODE_SCHEME: "TestCIZ"
            BUNDLE_ID: "com.example.TestCIZ"
        groups:
          - sonarcloud_credentials
        xcode: 15.3
        cocoapods: default
      triggering:
        events:
          - pull_request
        branch_patterns:
          - pattern: main
            include: true
            source: false
      scripts:
        - name: Install Sonar Scanner
          script: | 
            brew install sonar-scanner
        - name: Generate debug build
          script: | 
            xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2' \
            -derivedDataPath Build/ \
            -enableCodeCoverage YES \
            clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
        - name: Convert coverage report to Sonarqube format
          script: |             
            bash xccov-to-sonarqube-generic.sh Build/Logs/Test/*.xcresult/ > sonarqube-generic-coverage.xml
        - name: Generate and upload code analysis report
          script: |  
            export PATH=$PATH:$FCI_BUILD_DIR/sonar-scanner/bin
            
            sonar-scanner \
            -Dsonar.projectKey=$SONAR_PROJECT_KEY \
            -Dsonar.organization=$SONAR_ORG_KEY \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.projectVersion=1.0.0 \
            -Dsonar.sources=. \
            -Dsonar.cfamily.build-wrapper-output.bypass=true \
            -Dsonar.coverageReportPaths=sonarqube-generic-coverage.xml \
            -Dsonar.c.file.suffixes=- \
            -Dsonar.cpp.file.suffixes=- \
            -Dsonar.objc.file.suffixes=- \
