name: continuous-integration-action
description: Action for continuous integration
inputs:
  SONAR_PROJECT_KEY:
    description: Sonarqube project key
    required: true
  SONAR_HOST_URL:
    description: Sonarqube host url
    required: true
  SONARQUBE_TOKEN:
    description: Sonarqube token
    required: true
  #MIN_COVERAGE_VALUE:
    #description: Minimum coverage value
    #required: false
    #default: 40
    #type: integer
  #MIN_BUGS_VALUE:
    #description: Minimum bugs value
    #required: false
    #default: 0
    #type: integer
  #MIN_HOTSPOTS_VALUE:
    #description: Minimum hotspots value
    #required: false
    #default: 0
    #type: integer
  #MIN_EFFORT_VALUE:
    #description: Minimum effort value
    #required: false
    #default: 60
    #type: integer

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3

    - name: Make some tests
      run: |
      echo ${{ inputs.SONAR_PROJECT_KEY }}
      #echo "${{ inputs.SONAR_HOST_URL }}"
      #echo "${{ inputs.SONARQUBE_TOKEN }}"
      shell: bash
    
      


