name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:

    runs-on: macos-14

    steps:
    - uses: actions/checkout@v3

    - name: Xcode Setup
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.3'
    
    - name: Build
      run: |
        xcodebuild build -project TestCIZ.xcodeproj -scheme TestCIZ clean build -sdk iphoneos CODE_SIGNING_ALLOWED=No
    - name: Run tests
      run: |
        xcodebuild test -project TestCIZ.xcodeproj -scheme TestCIZ clean build -sdk iphoneos -destination "platform=iOS Simulator,OS=17.4,name=iPhone 14 Plus" CODE_SIGNING_ALLOWED=No

