name: continuous-integration-action
author: zlopez
description: Action for continuous integration
inputs:
  #Sonarqube options
  SONAR_PROJECT_NAME:
    description: Sonarqube project name
    required: true
env:
  COVERAGE_VALUE: 0
  BUGS_VALUE: 0
  HOTSPOTS_VALUE: 0
  EFFORT_VALUE: 0


runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - name: make some tests
      run: echo ${{ inputs.SONAR_PROJECT_NAME }}
