name: Template

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  testing:
    name: Testing
    runs-on: macos-14
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Execute Continuous Integration Action
      uses: ./.github/workflows/action.yml
      with:
        SONAR_PROJECT_NAME: ${{ secrets.SONAR_PROJECT_KEY }}


    
    
    
    
          
    
          
    
    
    
    

      

